### ISSUE TITLE
Add comments on Building Permit map

### ISSUE THREAD

**Issue by noemata83** [codefordurham/affordablehousing#3]

**Comment by chrisketchel** [comment]
hello

**Comment by chrisketchel** [comment]
Can we generate a live monthly feed for 
Durham Building Permit Activity?

for example 
Begin date: Mon Jan 01 2017
End Date: Sat Dec 31 2017
Building Type: Single Family House 
Building Activity: New
Permit Status: Issued (permit)
Number of Records in Current View: 762

**Comment by chrisketchel** [comment]
I will talk to Anise (city) about mimicking Tucker's changes, and ask how data is being updated.
