### ISSUE TITLE
Review wireframes

### ISSUE THREAD

**Issue by danforthdesign** [codefordurham/affordablehousing#31]
I've created wireframes for how the site would work on a mobile device and on a tablet or computer: http://lpmo40.axshare.com/#p=iphone_frame_for_desktop_view 

I created three graphs in the wireframes using some of the existing data, but a lot of the data sources do not seem to be accurate or are not well-documented.

**Comment by ronstebelton** [comment]
Data integrity and freshness has been a challenge, for sure.

Super excited about having wireframes!

Are you looking for any specific feedback on these, Janet?

**Comment by danforthdesign** [comment]
Probably the best feedback right now would be if the layouts make sense based on our existing content. When we hear back from enough people, I can revise these wireframes or move into visual design.

Feedback on the individual graphs would be helpful too, but not crucial to moving forward with the site as a whole. I think it would be good practice to work out a rough wireframe of each graph moving forward so we can see if our data makes sense.

**Comment by ronstebelton** [comment]
How do you think this will this be when we have a larger number of graphs?  Do we limit the number of graphs to keep it usable?  Do we need to have some navigation?  Maybe some accordion functionality?  Even with accordion functionality, it could be less usable on a smaller screen.  Maybe we limit based on the device you are using.  Maybe I'm just worrying about a non-problem.

Do you have ideas on how maps will fit into the equation?

I do think we want to make this product in a way that we could update content and use it for another data hub project.  It seems reasonable based on what I see here, but want to make sure we state that as an objective.

The legend for "Percentage of Household..." is overlaying the graph.  I wonder if we can find a way to put it above the graph like in the "Household Income...".  I think it would be easier to code up if we did.

**Comment by danforthdesign** [comment]
I've updated the wireframes based on this feedback at the same link above ( http://lpmo40.axshare.com/#p=iphone_frame_for_desktop_view ) with a sample map in one of the panels. I also added a filtering system for when we have more content to keep users from scrolling forever. 

It makes sense to use this structure as a template for other datahub projects but it could get confusing to have too many data topics in this one site.

I'd love to get more feedback before moving to styling these wireframes!

**Comment by adamajm** [comment]
Thanks - Janet - this is great! I think topic/tagged visualizations is a really useful, simple and flexible scheme for exploring different collections of data vizualizations. One suggestion to consider might be (primarily for website version as discussed) to add a "Key Metric" for each chart that we could include in the metadata that would display to the right of the "Title" bar. For example, see how these Metrics are displayed here: http://www.civicdashboards.com/city/durham-nc-16000US3719000/. So for the " Number of Housing Units per Resident" we'd have "[2.3 (2014)](http://www.civicdashboards.com/city/durham-nc-16000US3719000/persons_per_household)" next to it
